pipeline:
  identifier: Build_arrularthar_harness_ci_example_1709483221875
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: Harness_POC
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1708491840199
        repoName: arrularthar/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
